version: "3.7"

networks:
  bigdata:
    driver: bridge
    external: true

services:
  hive:
    image: hive-server:3.1.3
    build: images/hive 
    container_name: hive-server
    networks:
      - bigdata

  postgres:
    image: postgres:12
    container_name: postgres 
    restart: always
    ports:
      - 5433:5432
    networks:
      - bigdata
    environment:
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_USER=$PG_USER
      - POSTGRES_DB=$PG_DB
      - POSTGRES_HOST_AUTH_METHOD=md5 
      - TZ=Asia/Jakarta